### PR TITLE
removed commons-lang dependency

### PR DESCRIPTION
**Pull request by mmoayyed**
Handles #115

### CODE REVIEW

**Comment by battags** [comment]
+1

**Comment by leleuj** [comment]
I'm not sure it's such a good idea to remove the `commons-lang3` library and add 200 lines of source code instead. It's such a common and basic library which has no dependencies.

**Comment by mmoayyed** [comment]
I am really ambivalent here, though I would like it removed. Deploying the client in non-maven environments is painful when you have more than absolutely-required dependencies. As Scott rightly pointed out, it's only used for a handful of functions and we are not heavily dependent on it. In some ways, I'd like the client to be as much self-contained as possible.

This is also true with commons-codec by the way, a jar that is close to 2MB (or maybe less, not sure) and we only use "one function" in there! What gives?

**Comment by leleuj** [comment]
I'm in line to limit the dependencies as much as possible.

Here is the deal with `commons-lang3` : either we add 200 lines of source code or we keep one jar of 424 ko. I'd prefer the latter solution, but if there is a agreement to remove it, let's do it.

**Comment by battags** [comment]
I tend to prefer minimizing our dependencies to reduce conflict when being used in another application. (when we are the application, i.e. CAS Server, I care much less :-))

**Comment by mmoayyed** [comment]
:+1: to remove. We can always bring it back.

**Pull request merged**
