### PR TITLE
CASC-210: Added support for having regex expressions in the proxy (chaining) list.

### PR DESCRIPTION
**Pull request by jtgasper3**

### CODE REVIEW

**Comment by mmoayyed** [comment]
We also want to consider this for 3.4 given that it's been available for a while.

**Comment by mmoayyed** [comment]
Any other comments? Are we good to move fwd with this?

**Comment by battags** [comment]
Since it hasn't been looked at in almost a year, its probably worth giving it some time to be reviewed now that its been brought to our attention again.

**Comment by leleuj** [comment]
This pull request cannot be merge automatically. It must be rebased with the master.

**Comment by jtgasper3** [comment]
Merged with master... Should be good to review now.

**Comment by mmoayyed** [comment]
I had a look at this one again. This looks good to me, except now I think about it, I dont see a point to having a ExactUrlPatternMatcherStrategy. A regex strategy is by default an exact strategy with the extra ability to parse patterns. If you dont use a pattern, it will use an exact matching algorithm right? So why have both?

**Comment by battags** [comment]
+1

**Comment by battags** [comment]
Should this be the last major item before we cut 3.4?  I'm on vacation for the next two weeks so this would be the perfect time to do a 3.4 release :-)

**Comment by mmoayyed** [comment]
That IS perfecting timing :) My vote is, let's move forward with the release. I dont have much else to work on, maybe #111 but that can definitely be delayed.

**Comment by battags** [comment]
I am assuming you are +1, @mmoayyed ?

**Comment by mmoayyed** [comment]
Sure. :+1:

**Pull request merged**
