### PR TITLE
URIBuilder test cases

### PR DESCRIPTION
**Pull request by mmoayyed**

### CODE REVIEW

**Comment by mmoayyed** [comment]
So Travis tells me I have broken the build, but all tests pass locally just fine. @leleuj any ideas? 

This is what's failing:

```
Tests in error: 
  testNoResponse(org.jasig.cas.client.validation.Cas20ServiceTicketValidatorTests)
  testYesResponseButNoPgt(org.jasig.cas.client.validation.Cas20ServiceTicketValidatorTests)
  testYesResponseWithPgt(org.jasig.cas.client.validation.Cas20ServiceTicketValidatorTests)
```

**Comment by mmoayyed** [comment]
It may be sudo/port related.

**Comment by leleuj** [comment]
+1 for the comprehensive set of tests.

About the test failures, I find we're back to the issue we already had. Will remove the `sudo` to see.

**Comment by leleuj** [comment]
I just removed `sudo`. Can you do some update (remove the useless blank line at the end of the test class for example) on your pull request to launch again the Travis build?

**Comment by mmoayyed** [comment]
You can easily restart the build: https://travis-ci.org/Jasig/java-cas-client/builds/75327925

Though I am not sure if changes to master affect pulls. I wonder if should modify the travis build file inside the pull?

**Comment by leleuj** [comment]
Yes, I know, but I didn't want to launch it manually, but automatically. To be in the same conditions than in the previous build (maybe it doesn't matter, but I prefer to be cautious).

**Comment by mmoayyed** [comment]
Not sure that makes a different but I can try. The restart did fail as well.

**Comment by mmoayyed** [comment]
OK, here are some fake edits. Build is restarted automatically.

**Comment by leleuj** [comment]
And now it works. Let's keep things that way for now and we'll see if we ever get a unexpected broken build for a PR with this configuration.

**Comment by mmoayyed** [comment]
Excellent.

**Comment by battags** [comment]
+1

**Pull request merged**
