### PR TITLE
Upgrade to commons-lang3

### PR DESCRIPTION
**Pull request by mmoayyed**
Handles #103

### CODE REVIEW

**Comment by battags** [comment]
+1 (though honestly if that is the only place we use Commons-Lang it might not be worth the dependency)

**Comment by mmoayyed** [comment]
Sure thing; I can investigate what it would take to remove it. Could we do that in a separate pull?

**Comment by battags** [comment]
Yes -- sorry if that was not clear.  Not suggesting we do anything in this pull other than upgrade Commons Lang (which I gave a +1)

**Comment by mmoayyed** [comment]
cool! I sort of anticipated your response which prompted me to create #115 :)

**Pull request merged**
