### PR TITLE
Deploy SNAPSHOTs to Sonatype

### PR DESCRIPTION
**Pull request by leleuj**

### CODE REVIEW

**Comment by mmoayyed** [comment]
:+1:

**Comment by battags** [comment]
Are the test failures transient errors?

**Comment by mmoayyed** [comment]
We should probably review this. The failures are more than a few to be just transient. I cant duplicate them locally, but I am not running the build in a container.

**Comment by leleuj** [comment]
Indeed, it works locally. I see a few "Connection refused", I will investigate.

**Comment by leleuj** [comment]
I made a few tests and things are pretty strange:
- build https://travis-ci.org/Jasig/java-cas-client/builds/72958336 is marked "passed" as though it exited with value 1 and several tests are failing / it runs on the container-based infrastructure
- build https://travis-ci.org/Jasig/java-cas-client/builds/73341373 is marked "passed" and indeed, it seems to as it exited with value 0 and all tests pass / it runs on the old infrastructure
- build https://travis-ci.org/Jasig/java-cas-client/builds/73342649 is marked "failed" and indeed, it exited with value 1 and tests are failing / it runs on the container-based infrastructure.

I'm not sure if there is a real issue there and even if it's the case, we just need to move back to the old infrastructure. So I propose to merge the PR "as is" and remove "sudo: false" in the `.travis.yml` file to move back to the old infrastructure if necessary.

@battags @mmoayyed : agreed?

**Comment by mmoayyed** [comment]
Agreed.

**Comment by leleuj** [comment]
OK. I'm going to merge this one and see if I need to fix things.

**Pull request merged**
