### PR TITLE
CASC-217: Update the ticket validators to point to the new endpoint

### PR DESCRIPTION
**Pull request by leleuj**

### CODE REVIEW

**Comment by mmoayyed** [comment]
:+1:

**Comment by leleuj** [comment]
Waiting for @battags's feedback or new superseding PR.

**Comment by battags** [comment]
I'm not against this change.  I had spoken with @leleuj that I might do some refactoring so we don't need to create new filters each time.  My recommendation is to keep this open in case I can't come up with a viable alternative but not push it yet since I don't want to push it and then delete it.

**Comment by leleuj** [comment]
Exactly. What is our deadline on this? Do you plan a new 3.4.0 release after?

**Comment by mmoayyed** [comment]
I would be OK with pushing this change for now, and deleting/deprecating it later. This is a change that is very much requested and in demand right now, and I'd rather we not postpone its availability. Unless we can determine that that the refactoring effort can happen just in time before this upcoming release, it makes sense to just push this and cut a release, and work on the effort in the future with ease.

**Comment by leleuj** [comment]
That really makes sense if we cut the release after the merge. I'm willing to do the release if @battags can't handle it.

**Comment by battags** [comment]
I'd rather not introduce a class we're not sure if we want to keep.   This is code that people will start to leverage, we need to be careful about adding and then removing things (or having to support it).  We've been bitten in the past by NOT paying attention to that and had to cut releases where we added stuff back.  I'm in the process of attempting to leverage our new Protocol enum to help with creating the correct instances. (I also assuming we want the CAS30 Validator to retrieve attributes correctly?)

**Comment by leleuj** [comment]
Yes,we want the Cas30Validator to retrieve attributes correctly.
Yes, we should avoid introducing classes we don't want to keep, but isn't it such a big deal? We deprecate in the n+1 version and remove in the n+2 version.
If you're working on this, that's great! If you can't in a reasonable delay, I'm for a merge and release.

**Comment by mmoayyed** [comment]
So I guess the question is, do we have a sense of time as for when the new changes might become available? Would it be too bold to set a due date and if not met, proceed with the release?

**Comment by battags** [comment]
+1

**Comment by leleuj** [comment]
Thanks. Fully tested on: https://github.com/leleuj/java-jasig-cas-client-demo/commit/b68b21d148943cd901e69e4d36f0eff55d683561

**Pull request merged**
